"""
Extended built-in pronunciation library for Audify.

Merged into DEFAULT_PRONUNCIATION (config.py). Focus: the words a developer
working with Python, Windows, git/GitHub, AI/LLM tooling and web stacks reads
every day, where TTS engines (especially offline Kokoro) guess wrong.

Matching rules (see clean_text.apply_pronunciations):
  * ALL-CAPS keys match only in capitals, so acronyms never hijack plain words.
  * lowercase keys also match when capitalised at a sentence start.
  * Mixed-case keys match any casing. Every key respects word boundaries.

Spelled-out letters use spaces ("A P I"); words use rough phonetics.
"""

LIBRARY: dict[str, str] = {
    # -- AI / LLM ------------------------------------------------------------------
    "OpenAI": "open A I",
    "xAI": "X A I",
    "DeepSeek": "deep seek",
    "Qwen": "chwen",
    "Mixtral": "mix-trahl",
    "Ollama": "oh-llama",
    "LangChain": "lang chain",
    "LlamaIndex": "llama index",
    "vLLM": "V L L M",
    "Copilot": "co-pilot",
    "Wispr": "whisper",
    "Kokoro": "koh-koh-roh",
    "ONNX": "onyx",
    "CUDA": "koo-da",
    "cuDNN": "koo D N N",
    "TPU": "T P U",
    "NPU": "N P U",
    "VRAM": "V RAM",
    "RLHF": "R L H F",
    "LoRA": "lora",
    "QLoRA": "Q lora",
    "GGUF": "G G U F",
    "TTS": "T T S",
    "STT": "S T T",
    "ASR": "A S R",
    "OCR": "O C R",
    "MCP": "M C P",
    "RAG": "rag",
    "AGI": "A G I",
    "MoE": "M O E",
    "SFT": "S F T",
    "DPO": "D P O",
    "PPO": "P P O",
    "SOTA": "so-ta",
    "GPT-3.5": "G P T 3 point 5",
    "GPT-4": "G P T 4",
    "GPT-4o": "G P T 4 oh",
    "GPT-5": "G P T 5",
    "LLaMA": "llama",
    "agentic": "a-jen-tick",
    "multimodal": "multi-modal",
    "PyTorch": "pie torch",
    "NumPy": "num pie",
    "SciPy": "sigh pie",
    "Jupyter": "jupiter",
    "ipynb": "I pie notebook",
    "HuggingFace": "hugging face",
    "ChatGPT's": "Chat G P T's",
    "Anthropic's": "an-throp-ic's",
    "Claude's": "clawed's",
    "Claude": "clawed",

    # -- Python --------------------------------------------------------------------
    "__init__": "dunder init",
    "__main__": "dunder main",
    "__name__": "dunder name",
    "__init__.py": "dunder init dot pie",
    "__main__.py": "dunder main dot pie",
    "**kwargs": "double star keyword args",
    "*args": "star args",
    "kwargs": "keyword args",
    "elif": "else if",
    "stdlib": "standard lib",
    "stdin": "standard in",
    "stdout": "standard out",
    "stderr": "standard error",
    "argv": "arg V",
    "argparse": "arg parse",
    "asyncio": "ay-sink I O",
    "aiohttp": "A I O H T T P",
    "urllib": "U R L lib",
    "ctypes": "C types",
    "cffi": "C F F I",
    "getattr": "get atter",
    "setattr": "set atter",
    "hasattr": "has atter",
    "isinstance": "is instance",
    "repr": "repper",
    "f-string": "F string",
    "f-strings": "F strings",
    "virtualenv": "virtual env",
    "pipx": "pip X",
    "pytest": "pie test",
    "mypy": "my pie",
    "pydantic": "pie dantic",
    "matplotlib": "mat plot lib",
    "pyplot": "pie plot",
    "PyInstaller": "pie installer",
    "Nuitka": "noo-it-ka",
    "tkinter": "T K inter",
    "ttk": "T T K",
    "pygame": "pie game",
    "pystray": "pie stray",
    "pynput": "pie input",
    "pyperclip": "pie per clip",
    "PyQt": "pie cute",
    "PySide": "pie side",
    "miniaudio": "mini audio",
    "onnxruntime": "onyx runtime",
    "uvicorn": "you-vee-corn",
    "PIL": "pill",
    "dataclass": "data class",
    "dataclasses": "data classes",
    "requirements.txt": "requirements dot text",
    "setup.py": "setup dot pie",
    "pyproject.toml": "pie project dot tom-ul",

    # -- File extensions -----------------------------------------------------------
    ".py": " dot pie",
    ".pyc": " dot pie C",
    ".pyw": " dot pie W",
    ".exe": " dot E X E",
    ".msi": " dot M S I",
    ".dll": " dot D L L",
    ".bat": " dot bat",
    ".cmd": " dot C M D",
    ".ps1": " dot P S 1",
    ".sh": " dot S H",
    ".md": " dot M D",
    ".txt": " dot text",
    ".json": " dot jason",
    ".jsonl": " dot jason L",
    ".yaml": " dot yamel",
    ".yml": " dot yamel",
    ".toml": " dot tom-ul",
    ".ini": " dot I N I",
    ".cfg": " dot config",
    ".env": " dot env",
    ".csv": " dot C S V",
    ".xlsx": " dot excel",
    ".docx": " dot doc X",
    ".pdf": " dot P D F",
    ".html": " dot H T M L",
    ".css": " dot C S S",
    ".js": " dot J S",
    ".ts": " dot T S",
    ".jsx": " dot J S X",
    ".tsx": " dot T S X",
    ".png": " dot P N G",
    ".jpg": " dot J peg",
    ".jpeg": " dot J peg",
    ".svg": " dot S V G",
    ".ico": " dot icon",
    ".gif": " dot gif",
    ".webp": " dot web P",
    ".mp3": " dot M P 3",
    ".mp4": " dot M P 4",
    ".wav": " dot wave",
    ".zip": " dot zip",
    ".log": " dot log",
    ".iss": " dot I S S",
    ".onnx": " dot onyx",
    ".gitignore": " dot git ignore",
    ".sln": " dot solution",
    ".csproj": " dot C S proj",

    # -- Windows -------------------------------------------------------------------
    "PowerShell": "power shell",
    "cmd": "C M D",
    "WSL": "W S L",
    "WSL2": "W S L 2",
    "winget": "win get",
    "regedit": "reg edit",
    "HKLM": "H K L M",
    "HKCU": "H K C U",
    "UAC": "U A C",
    "DPI": "D P I",
    "DWM": "D W M",
    "Win32": "win 32",
    "Win11": "Windows 11",
    "Win10": "Windows 10",
    "x64": "X 64",
    "x86": "X 86",
    "ARM64": "arm 64",
    "AppData": "app data",
    "LocalAppData": "local app data",
    "System32": "system 32",
    "exe": "E X E",
    "DLL": "D L L",
    "DLLs": "D L Ls",
    "MSI": "M S I",
    "NTFS": "N T F S",
    "BSOD": "B S O D",
    "WinUI": "win U I",
    "WPF": "W P F",
    "WinForms": "win forms",
    "ISCC": "I S C C",
    "OBS": "O B S",
    "CapCut": "cap cut",
    "WhatsApp": "whats app",
    "Raycast": "ray cast",

    # -- git / GitHub / collaboration ----------------------------------------------
    "monorepo": "mono repo",
    "repo": "ree-po",
    "repos": "ree-pos",
    "gh": "G H",
    "CI": "C I",
    "CD": "C D",
    "CI/CD": "C I C D",
    "SHA": "shah",
    "SHA-1": "shah 1",
    "SHA-256": "shah 256",
    "WIP": "work in progress",
    "LGTM": "looks good to me",
    "PTAL": "please take a look",
    "TL;DR": "too long, didn't read",
    "TLDR": "too long, didn't read",
    "IMO": "in my opinion",
    "IMHO": "in my humble opinion",
    "FYI": "for your information",
    "AFAIK": "as far as I know",
    "IIRC": "if I remember correctly",
    "TBD": "to be determined",
    "TBA": "to be announced",
    "ETA": "E T A",
    "EOD": "end of day",
    "EOW": "end of week",
    "OOO": "out of office",
    "BTW": "by the way",
    "AKA": "also known as",
    "aka": "also known as",
    "w.r.t.": "with respect to",
    "cf.": "compare",
    "viz.": "namely",
    "YMMV": "your mileage may vary",
    "TIL": "today I learned",
    "ELI5": "explain like I'm five",
    "WFH": "work from home",
    "LMK": "let me know",
    "NVM": "never mind",
    "TBH": "to be honest",
    "IDK": "I don't know",
    "ICYMI": "in case you missed it",
    "RSVP": "R S V P",
    "DM": "D M",
    "DMs": "D Ms",
    "OP": "O P",
    "EOL": "E O L",
    "OKR": "O K R",
    "OKRs": "O K Rs",
    "KPI": "K P I",
    "KPIs": "K P Is",
    "ROI": "R O I",
    "SLA": "S L A",
    "SLO": "S L O",
    "MVP": "M V P",
    "PoC": "proof of concept",
    "POC": "P O C",
    "B2B": "B to B",
    "B2C": "B to C",
    "Q&A": "Q and A",
    "R&D": "R and D",
    "1:1": "one on one",

    # -- Web / backend / frontend --------------------------------------------------
    "Node.js": "node J S",
    "Next.js": "next J S",
    "Vue": "view",
    "Vue.js": "view J S",
    "Vite": "veet",
    "Svelte": "svelt",
    "SvelteKit": "svelt kit",
    "shadcn": "shad C N",
    "JSX": "J S X",
    "TSX": "T S X",
    "DOM": "dom",
    "SCSS": "S C S S",
    "Deno": "dee-no",
    "tRPC": "T R P C",
    "gRPC": "G R P C",
    "RPC": "R P C",
    "useEffect": "use effect",
    "useState": "use state",
    "useRef": "use ref",
    "pnpm": "P N P M",
    "npm's": "N P M's",
    "SPA": "S P A",
    "SSR": "S S R",
    "SSG": "S S G",
    "PWA": "P W A",
    "SEO": "S E O",
    "WebSocket": "web socket",
    "WebSockets": "web sockets",
    "WebRTC": "web R T C",
    "WebGL": "web G L",
    "SSE": "S S E",
    "HTTP/2": "H T T P 2",
    "HTTP/3": "H T T P 3",
    "UTF-8": "U T F 8",
    "UTF-16": "U T F 16",
    "ASCII": "ask-ee",
    "Base64": "base 64",
    "MD5": "M D 5",
    "RSA": "R S A",
    "AES": "A E S",
    "HMAC": "H mac",
    "CRLF": "C R L F",
    "LF": "L F",
    "IPv4": "I P V 4",
    "IPv6": "I P V 6",
    "IP": "I P",
    "IPs": "I Ps",
    "DHCP": "D H C P",
    "LAN": "lan",
    "WAN": "wan",
    "WiFi": "wifi",
    "Wi-Fi": "wifi",
    "SMB": "S M B",
    "NAS": "nas",
    "SQLite": "S Q L lite",
    "DynamoDB": "dynamo D B",
    "DB": "D B",
    "DBs": "D Bs",
    "ORM": "O R M",
    "CMS": "C M S",
    "CRM": "C R M",
    "ERP": "E R P",
    "Postgres": "post-gres",
    "PostHog": "post hog",
    "Netlify": "net-li-fy",
    "Heroku": "heh-roh-koo",
    "Grafana": "gra-fah-na",
    "RabbitMQ": "rabbit M Q",
    "Elasticsearch": "elastic search",
    "Auth0": "auth zero",
    "SSO": "S S O",
    "SAML": "sam-ul",
    "OIDC": "O I D C",
    "RBAC": "R back",
    "mTLS": "M T L S",
    "2FA": "two factor",
    "MFA": "M F A",
    "OTP": "O T P",
    "CAPTCHA": "cap-cha",
    "localhost:3000": "localhost port 3000",
    "localhost:8000": "localhost port 8000",
    "localhost:8080": "localhost port 8080",
    "127.0.0.1": "local host I P",
    "ID": "I D",
    "IDs": "I Ds",
    "UUIDs": "U U I Ds",
    "OS": "O S",
    "i18n": "internationalization",
    "l10n": "localization",
    "a11y": "accessibility",

    # -- Cloud / DevOps ------------------------------------------------------------
    "k8s": "koo-ber-net-eez",
    "K8s": "koo-ber-net-eez",
    "EC2": "E C 2",
    "S3": "S 3",
    "IAM": "I A M",
    "VPC": "V P C",
    "SRE": "S R E",
    "IaC": "infrastructure as code",
    "on-prem": "on premises",
    "Terraform": "terra-form",
    "Dockerfile": "docker file",
    "docker-compose": "docker compose",
    "YAMLs": "yamels",
    "crontab": "cron tab",
    "systemd": "system D",
    "SIGINT": "sig int",
    "SIGTERM": "sig term",
    "PID": "P I D",
    "PIDs": "P I Ds",
    "OOM": "out of memory",

    # -- Languages & toolchains ----------------------------------------------------
    "C++": "C plus plus",
    "C#": "C sharp",
    "F#": "F sharp",
    ".NET": "dot net",
    "ASP.NET": "A S P dot net",
    "Obj-C": "objective C",
    "rustc": "rust C",
    "Golang": "go lang",
    "PHP": "P H P",
    "MATLAB": "mat lab",
    "Qt": "cute",
    "GTK": "G T K",
    "Tauri": "tow-ree",
    "SwiftUI": "swift U I",
    "Xcode": "X code",
    "JVM": "J V M",
    "JDK": "J D K",
    "LLVM": "L L V M",
    "GCC": "G C C",
    "MSVC": "M S V C",
    "CMake": "C make",
    "WASI": "wazzy",
    "JIT": "jit",
    "AOT": "A O T",
    "GC": "G C",
    "VM": "V M",
    "VMs": "V Ms",
    "CLIs": "C L Is",
    "SDKs": "S D Ks",
    "IDEs": "I D Es",
    "GPUs": "G P Us",
    "CPUs": "C P Us",

    # -- Operators & symbols -------------------------------------------------------
    "==": " double equals ",
    "+=": " plus equals ",
    "-=": " minus equals ",
    "*=": " times equals ",
    "/=": " divide equals ",
    "::": " double colon ",
    "<-": " left arrow ",
    "~/": " home slash ",

    # -- Units & sizes -------------------------------------------------------------
    "KB": "kilobytes",
    "MB": "megabytes",
    "GB": "gigabytes",
    "TB": "terabytes",
    "GHz": "gigahertz",
    "MHz": "megahertz",
    "kHz": "kilohertz",
    "Mbps": "megabits per second",
    "Gbps": "gigabits per second",
    "FPS": "F P S",
    "fps": "F P S",
    "ms": "milliseconds",
    "RPM": "R P M",
    "WPM": "words per minute",
    "p99": "P 99",
    "p95": "P 95",

    # -- Everyday apps & services --------------------------------------------------
    "YouTube": "you tube",
    "TikTok": "tick tock",
    "LinkedIn's": "linked in's",
    "Zapier": "zappy-er",
    "n8n": "N 8 N",
    "Airtable": "air table",
    "ClickUp": "click up",
    "Pinokio": "pin-oh-kee-oh",
    "Gmail": "G mail",
    "iCloud": "I cloud",
    "iPhone": "I phone",
    "iPad": "I pad",
    "macOS's": "mac O S's",
    "PayPal": "pay pal",
    "eBay": "E bay",
}
